from .button import button
from .wires import wires
from .maze import maze
from .simonsays import simonsays
from .keypad import keypad
from .whosonfirst import whosonfirst
from .bigcircle import bigcircle
from .listening import listening
from .wordscramble import wordscramble
from .password import password
from .morsecode import morsecode
from .twobits import twobits
from .crazytalk import crazytalk
from .laundry import laundry
from .anagrams import anagrams
from .roundkeypad import roundkeypad
from .colorflash import colorflash
from .poker import poker
from .skewedslots import skewedslots
from .shapeshift import shapeshift
from .orientationcube import orientationcube
from .turnthekeys import turnthekeys
from .combinationlock import combinationlock
from .bitwiseoperations import bitwiseoperations
from .cryptography import cryptography
from .simonstates import simonstates
# from .yahtzee import yahtzee
from .wordsearch import wordsearch
from .gamepad import gamepad
from .rubikscube import rubikscube
from .safetysafe import safetysafe
from .semaphore import semaphore
from .ledencryption import ledencryption
from .mortalkombat import mortalkombat
from .coloredsquares import coloredsquares
from .mysticsquare import mysticsquare
from .wastemanagement import wastemanagement
from .pointoforder import pointoforder
from .complicatedwires import complicatedwires
from .minesweeper import minesweeper
from .chess import chess
from .perplexingwires import perplexingwires
from .maintenance import maintenance
from .visualimpairment import visualimpairment
from .brokenbuttons import brokenbuttons
from .ledgrid import ledgrid
from .coloredswitches import coloredswitches
from .painting import painting
from .plumbing import plumbing
from .caesarcipher import caesarcipher
from .letterkeys import letterkeys
from .monsplodefight import monsplodefight
from .pianokeys import pianokeys
from .symbolicpassword import symbolicpassword
from .fastmath import fastmath
from .wireplacement import wireplacement
from .followtheleader import followtheleader
# from .battleship import battleship
from .fizzbuzz import fizzbuzz
from .perspectivepegs import perspectivepegs
from .creation import creation
from .doubleoh import doubleoh
from .tictactoe import tictactoe
from .numberpad import numberpad
from .cheapcheckout import cheapcheckout
from .booleanvenndiagram import booleanvenndiagram
from .modulesagainsthumanity import modulesagainsthumanity
from .neutralization import neutralization
from .probing import probing
from .friendship import friendship
from .complicatedbuttons import complicatedbuttons
from .adjacentletters import adjacentletters
from .sillyslots import sillyslots