from .adjacentletters import adjacentletters
from .adventuregame import adventuregame
from .algebra import algebra
from .alphabet import alphabet
from .anagrams import anagrams
from .astrology import astrology
from .bigcircle import bigcircle
from .binaryled import binaryled
from .binarypuzzle import binarypuzzle
from .bitmaps import bitmaps
from .bitwiseoperations import bitwiseoperations
from .blindalley import blindalley
from .blindmaze import blindmaze
from .booleanvenndiagram import booleanvenndiagram
from .brokenbuttons import brokenbuttons
from .bulb import bulb
from .button import button
from .caesarcipher import caesarcipher
from .caesarsmaths import caesarsmaths
from .charactershift import charactershift
from .cheapcheckout import cheapcheckout
from .chess import chess
from .chordqualities import chordqualities
from .clock import clock
from .coloredsquares import coloredsquares
from .coloredswitches import coloredswitches
from .colormath import colormath
from .colourflash import colourflash
from .combinationlock import combinationlock
from .complicatedbuttons import complicatedbuttons
from .complicatedwires import complicatedwires
from .connectioncheck import connectioncheck
from .countdown import countdown
from .crazytalk import crazytalk
from .creation import creation
from .cryptography import cryptography
from .doubleoh import doubleoh
from .emojimath import emojimath
from .fastmath import fastmath
from .fizzbuzz import fizzbuzz
from .followtheleader import followtheleader
from .foreignexchangerates import foreignexchangerates
from .friendship import friendship
from .gamepad import gamepad
from .icecream import icecream
from .keypad import keypad
from .laundry import laundry
from .ledencryption import ledencryption
from .ledgrid import ledgrid
from .letterkeys import letterkeys
from .lightcycle import lightcycle
from .listening import listening
from .logic import logic
from .mahjong import mahjong
from .maintenance import maintenance
from .maze import maze
from .mazematics import mazematics
from .microcontroller import microcontroller
from .minesweeper import minesweeper
from .modulesagainsthumanity import modulesagainsthumanity
from .monsplodefight import monsplodefight
from .morsecode import morsecode
from .morsematics import morsematics
from .mortalkombat import mortalkombat
from .mouseinthemaze import mouseinthemaze
from .murder import murder
from .mysticsquare import mysticsquare
from .neutralization import neutralization
from .numberpad import numberpad
from .onlyconnect import onlyconnect
from .orientationcube import orientationcube
from .painting import painting
from .password import password
from .perplexingwires import perplexingwires
from .perspectivepegs import perspectivepegs
from .pianokeys import pianokeys
from .playfaircipher import playfaircipher
from .plumbing import plumbing
from .pointoforder import pointoforder
from .poker import poker
from .probing import probing
from .regularhexpressions import regularhexpressions
from .resistors import resistors
from .rhythms import rhythms
from .rockpaperscissorslizardspock import rpslsp
from .roundkeypad import roundkeypad
from .rubikscube import rubikscube
from .safetysafe import safetysafe
from .screw import screw
from .seashells import seashells
from .semaphore import semaphore
from .sevendeadlysins import sevendeadlysins
from .shapeshift import shapeshift
from .sillyslots import sillyslots
from .simonsays import simonsays
from .simonscreams import simonscreams
from .simonstates import simonstates
from .skewedslots import skewedslots
from .splittingtheloot import splittingtheloot
from .squarebutton import squarebutton
from .switches import switches
from .symbolicpassword import symbolicpassword
from .textfield import textfield
from .thirdbase import thirdbase
from .tictactoe import tictactoe
from .turnthekeys import turnthekeys
from .twobits import twobits
from .visualimpairment import visualimpairment
from .wastemanagement import wastemanagement
from .webdesign import webdesign
from .whosonfirst import whosonfirst
from .wireplacement import wireplacement
from .wires import wires
from .wordscramble import wordscramble
from .wordsearch import wordsearch
from .x01 import x01
from .zoo import zoo