from .button import button
from .wires import wires
from .maze import maze
from .simonsays import simonsays
from .keypad import keypad
from .whosonfirst import whosonfirst
from .bigcircle import bigcircle
from .listening import listening
from .wordscramble import wordscramble
from .password import password
from .morsecode import morsecode
from .twobits import twobits
from .crazytalk import crazytalk
from .laundry import laundry
from .anagrams import anagrams
from .roundkeypad import roundkeypad
from .colorflash import colorflash
from .poker import poker
from .skewedslots import skewedslots
from .shapeshift import shapeshift
from .orientationcube import orientationcube
from .turnthekeys import turnthekeys